---
# To validate YAML syntax:
# aws cloudformation validate-template --template-body file://parameters_test.yaml

# In order to get the Change Set: (All parameters should have default values or use the override)
# aws cloudformation deploy --template-file parameters_test.yaml --stack-name test --no-execute-changeset

# we create the cloudformation template
# aws cloudformation create-stack --stack-name test --template-body file://parameters_test.yaml --parameters file://0-parameters.json --region us-east-2
# aws cloudformation create-change-set --stack-name ${MODULES_TO_BUILD} --template-body file://${MODULES_TO_BUILD}/cfn_stack_spec.yaml --parameters file://${MODULES_TO_BUILD}/parameters.json --region us-east-2
# aws cloudformation update-stack --stack-name test --template-body file://parameters_test.yaml --parameters file://0-parameters.json --region us-east-2
# aws cloudformation list-stacks | jq .StackSummaries[].StackName
# aws cloudformation create-stack --capabilities CAPABILITY_IAM CAPABILITY_NAMED_IAM  --stack-name test --template-body file://cloudformation/template-asg.yaml --parameters file://config/params-asg.json --region us-east-2 --profile esteban

# some options:
# [--disable-rollback | --no-disable-rollback]
# [--rollback-configuration <value>]
# [--timeout-in-minutes <value>]
# [--notification-arns <value>]
# [--capabilities <value>]
# [--resource-types <value>]
# [--role-arn <value>]
# [--on-failure <value>]
# [--stack-policy-body <value>]
# [--stack-policy-url <value>]
# [--tags <value>]
# [--client-request-token <value>]
# [--enable-termination-protection | --no-enable-termination-protection]
# [--cli-input-json <value>]
# [--generate-cli-skeleton <value>]


LogicalID:
  Type: AWS::EC2::LaunchTemplate
  Properties:
    LaunchTemplateData:
      BlockDeviceMappings:
        -
      DisableApiTermination: false
      EbsOptimized: false
      ElasticGpuSpecifications:
        -
      ElasticInferenceAccelerators:
        -
      ImageId: "String"
      InstanceInitiatedShutdownBehavior: "String"
      InstanceType: "String"
      KernelId: "String"
      KeyName: "String"
      LicenseSpecifications:
        -
      NetworkInterfaces:
        -
      RamDiskId: "String"
      SecurityGroupIds:
        -
      SecurityGroups:
        -
      TagSpecifications:
        -
      UserData: "String"
    LaunchTemplateName: "String"
    TagSpecifications:
      TagSpecifications